Repository Me-Adota/website, pull requests merged in 2020-12, with the labels that each got.

#92 Dev/douglas castro/insert adoption data on home
  pages/views.py
  templates/account/email/base_message.txt
  templates/account/email/email_confirmation_message.txt
  templates/account/email/email_confirmation_subject.txt
  templates/account/email/password_reset_key_message.txt
  templates/account/email/password_reset_key_subject.txt
  templates/account/messages/email_confirmed.txt
  templates/pages/index.html
Labels: Back-end, Task

#95 Dev/douglas castro/insert adoption data on informations
  pages/views.py
  templates/pages/informations.html
Labels: Back-end, Task

#93 Dev/iagoomr/sprint v0.4
  templates/account/email_confirm.html
  templates/account/signup.html
  templates/account/verification_sent.html
Labels: Front-end, User Story, bug

#116 Dev/guilherme braz/fix validation
  pets/views.py
  users/views.py
Labels: Back-end, bug

#118 Dev/guilherme braz/fix migrate bug
  pets/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Back-end, bug
