Repository Me-Adota/website, pull requests merged in 2020-11, with the labels that each got.

#41 Dev/douglas castro/create users and pets models
  meAdota/settings.py
  pets/__init__.py
  pets/admin.py
  pets/apps.py
  pets/migrations/0001_initial.py
  pets/migrations/__init__.py
  pets/models.py
  pets/tests.py
  pets/views.py
  requirements.txt
  templates/account/account_inactive.html
  templates/account/base.html
  templates/account/email.html
  templates/account/email/base_message.txt
  templates/account/email/email_confirmation_message.txt
  templates/account/email/email_confirmation_signup_message.txt
  templates/account/email/email_confirmation_signup_subject.txt
  templates/account/email/email_confirmation_subject.txt
  templates/account/email/password_reset_key_message.txt
  templates/account/email/password_reset_key_subject.txt
  templates/account/email_confirm.html
  templates/account/login.html
  templates/account/logout.html
  templates/account/messages/cannot_delete_primary_email.txt
  templates/account/messages/email_confirmation_sent.txt
  templates/account/messages/email_confirmed.txt
  templates/account/messages/email_deleted.txt
  templates/account/messages/logged_in.txt
  templates/account/messages/logged_out.txt
  templates/account/messages/password_changed.txt
  templates/account/messages/password_set.txt
  templates/account/messages/primary_email_set.txt
  templates/account/messages/unverified_primary_email.txt
  templates/account/password_change.html
  templates/account/password_reset.html
  templates/account/password_reset_done.html
  templates/account/password_reset_from_key.html
  templates/account/password_reset_from_key_done.html
  templates/account/password_set.html
  templates/account/signup.html
  templates/account/signup_closed.html
  templates/account/snippets/already_logged_in.html
  templates/account/verification_sent.html
  templates/account/verified_email_required.html
  users/__init__.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Back-end

#44 Dev/joseguilhermefmoura/sprint v0.2
  meAdota/settings.py
  static/css/accounts.css
  static/img/common/paws_texture.jpg
  templates/account/base.html
  templates/account/login.html
  templates/account/signup.html
  templates/navbar.html
  users/forms.py
Labels: Back-end, Front-end

#45 Dev/douglas castro/create users and pets models
  meAdota/settings.py
  requirements.txt
  users/admin.py
  users/forms.py
  users/models.py
Labels: Back-end, hacktoberfest-accepted
