Repository Me-Adota/website, pull requests merged in 2020-10, with the labels that each got.

#1 Dev/b2198/backend creation
  .gitignore
  manage.py
  meAdota/__init__.py
  meAdota/asgi.py
  meAdota/settings.py
  meAdota/urls.py
  meAdota/wsgi.py
Labels: hacktoberfest-accepted

#2 :bulb: Add requirements
  requirements.txt
  runtime.txt
Labels: hacktoberfest-accepted

#3 Dev/douglas castro/readme and gitigone
  .gitignore
  README.md
Labels: hacktoberfest-accepted

#6 :bulb: Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#8 Closes #7:
  meAdota/settings.py
  meAdota/urls.py
  pages/__init__.py
  pages/admin.py
  pages/apps.py
  pages/migrations/__init__.py
  pages/models.py
  pages/tests.py
  pages/views.py
  static/css/index.css
  templates/base.html
  templates/footer.html
  templates/navbar.html
  templates/pages/index.html
Labels: enhancement, hacktoberfest-accepted

#9 Dev/douglas castro/readme
  README.md
Labels: documentation, hacktoberfest-accepted
